kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: drupal-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30085
    hostPort: 8085  # Puerto accesible solicitado
    protocol: TCP
